//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceManagementSystem.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestTracking
    {
        public int RequestTrackingId { get; set; }
        public Nullable<int> RequestStatusId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual RequestStatu RequestStatu { get; set; }
    }
}
