//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceManagementSystem.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Request
    {
        public int RequestId { get; set; }

        [DisplayName("Category")]
        public Nullable<int> DepartmentId { get; set; }
        public string RequestDescription { get; set; }
        public Nullable<int> RequestStatusId { get; set; }

        public virtual Department Department { get; set; }
        public virtual RequestStatu RequestStatu { get; set; }
    }
}
